server:
  port: 8090

spring:
  profiles:
    active: local

---

spring:
  profiles: local

dynamo:
  details:
    tableName: "TokenCounter"
    region: "us-west-2"
    endPoint: "http://localhost:8042"
    maxRetry: 3
    accessKey: abc
    secretKey: def
profile:
  counter:
    ttl:
      for24hrs: 60
      for30Days: 3600

---
spring:
  profiles: integration
dynamo:
  details:
    tableName: "TokenCounter"
    region: "us-west-2"
    accessKey: AKIAW3Z4C3AFY7HYQH73
    secretKey: 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
profile:
  counter:
    ttl:
      for24hrs: 60
      for30Days: 3600

